# Docs: https://docs.spring.io/spring-data/jpa/reference/jpa/getting-started.html
# Exemplo: https://github.com/ofernandobarbosa/minicurso-java-spring-solid
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

# Exemplo Mustache: https://github.com/IgorAvilaPereira/SpringStore/blob/main/spring_store/src/main/java/controller/ItemController.java
spring.mustache.prefix = classpath:/templates/
spring.mustache.suffix = .html
